global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '<TOKEN_HERE>'
        chat_id: <ID_HERE>
        parse_mode: 'Markdown'
        message: '{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Details:* {{ .Annotations.description }}\n\n{{ end }}'

