global:
  scrape_interval: 15s

rule_files:
  - "rules.yml"
  - "test_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '192.168.32.29:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.168.32.32:9100'
          - '192.168.32.148:9100'
          - '192.168.32.169:9100'
          - '192.168.32.232:9100'
          - '192.168.32.118:9100'
