global:
  scrape_interval: 15s

rule_files:
  - "rules.yml"
  - "test_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '<alertmanager>:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '<ip>:9100'
          - '<ip>:9100'
          - '<ip>:9100'
          - '<ip>:9100'
          - '<ip>:9100'
